# Generated by Django 4.1.5 on 2023-02-07 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_userprofile_address_userprofile_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='imgUrl',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, upload_to='profile_picture'),
        ),
    ]
